import = ["/home/naethiel/.config/alacritty/rose-pine/rose-pine.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[[keyboard.bindings]]
chars = "\u00021"
key = "&"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00022"
key = "é"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00023"
key = "\""
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00024"
key = "'"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00025"
key = "("
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00026"
key = "-"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00027"
key = "è"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00028"
key = "_"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00029"
key = "ç"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00020"
key = "à"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002%"
key = "D"
mods = "ALt"

[[keyboard.bindings]]
chars = "\u0002\""
key = "D"
mods = "Shift|ALt"

[[keyboard.bindings]]
chars = "\u0002z"
key = "Return"
mods = "Shift|Alt"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Alt"

[window]
decorations = "none"
