return {}
-- return {
--   "zbirenbaum/copilot.lua",
--   cmd = "Copilot",
--   event = "InsertEnter",
--   config = function()
--     require("copilot").setup({
--       panel = {
--         enabled = true,
--         auto_refresh = false,
--         keymap = {
--           jump_prev = "<leader>cn",
--           jump_next = "<leader>cp",
--           accept = "<CR>",
--           refresh = "<leader>cr",
--           open = "<M-c>",
--         },
--         layout = {
--           position = "bottom", -- | top | left | right
--           ratio = 0.4
--         },
--       },
--       suggestion = {
--         enabled = true,
--         auto_trigger = true,
--         debounce = 75,
--         keymap = {
--           accept = "<M-CR>",
--           accept_word = "<M-w>",
--           accept_line = false,
--           next = "<M-n>",
--           prev = "<M-p>",
--           dismiss = "<M-X>",
--         },
--       },
--       filetypes = {
--         yaml = false,
--         markdown = false,
--         help = false,
--         gitcommit = false,
--         gitrebase = false,
--         hgcommit = false,
--         svn = false,
--         cvs = false,
--         ["."] = false,
--       },
--       copilot_node_command = 'node', -- Node.js version must be > 18.x
--       server_opts_overrides = {},
--     })
--   end,
-- }
